version: '3.8'

services:
  webserver:
    image: 'nginx:alpine'
    container_name: 'questionnaire-webserver'
    restart: unless-stopped
    tty: true
    ports:
      - '127.0.0.1:${APP_PORT:-80}:80'
    volumes:
      - './:/var/www/html'
      - './docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf'
    networks:
      - main
    links:
      - symfony
    depends_on:
      - symfony
  symfony:
    image: "questionnaire/platform"
    container_name: 'questionnaire-platform'
    build:
      context: './docker/php'
      dockerfile: 'Dockerfile'
    ports:
      - "9000:9000"
    volumes:
      - './docker/php/php.ini:/opt/bitnami/php/etc/php.ini'
      - './docker/php/www.conf:/opt/bitnami/php/etc/php-fpm.d/www.conf'
      - '.:/var/www/html'
    networks:
      - main
    depends_on:
      - database

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    container_name: 'questionnaire-db'
    restart: unless-stopped
    ports:
      - '127.0.0.1:${FORWARD_DB_PORT:-5432}:5432'
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
       - ${PWD}/data/postgres:/var/lib/postgresql/data:rw
    networks:
      - main
###< doctrine/doctrine-bundle ###
networks:
  main:
    driver: bridge

