<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6n5uMF5\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6n5uMF5/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6n5uMF5.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6n5uMF5\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container6n5uMF5\App_KernelDevDebugContainer([
    'container.build_hash' => '6n5uMF5',
    'container.build_id' => 'b7599c3f',
    'container.build_time' => 1721946843,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container6n5uMF5');
