<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_index_index' => [[], ['_controller' => 'App\\Controller\\IndexController::index'], [], [['text', '/']], [], [], []],
    'app_questionnaire_index' => [[], ['_controller' => 'App\\Controller\\QuestionnaireController::index'], [], [['text', '/questionnaire/']], [], [], []],
    'app_questionnaire_answer' => [[], ['_controller' => 'App\\Controller\\QuestionnaireController::answer'], [], [['text', '/questionnaire/answer']], [], [], []],
    'user' => [[], ['_controller' => 'App\\Controller\\UserController::update'], [], [['text', '/user']], [], [], []],
    'App\Controller\IndexController::index' => [[], ['_controller' => 'App\\Controller\\IndexController::index'], [], [['text', '/']], [], [], []],
    'App\Controller\QuestionnaireController::index' => [[], ['_controller' => 'App\\Controller\\QuestionnaireController::index'], [], [['text', '/questionnaire/']], [], [], []],
    'App\Controller\QuestionnaireController::answer' => [[], ['_controller' => 'App\\Controller\\QuestionnaireController::answer'], [], [['text', '/questionnaire/answer']], [], [], []],
    'App\Controller\UserController::update' => [[], ['_controller' => 'App\\Controller\\UserController::update'], [], [['text', '/user']], [], [], []],
];
